project:
  type: website

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TWBDZMSNVY"
    anonymize-ip: true
  title: "Vespa velutina in Piemonte"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/cartografia.qmd
        text: Cartografia
      - text: Provincia di Torino
        menu:
          # - href: pages/to/attivita.qmd
          #   text: Trappolaggio
          - href: pages/to/catture.qmd
            text: Catture
          - href: pages/to/nidi.qmd
            text: Nidi
      - text: Provincia di Cuneo
        menu:
          # - href: pages/cn/attivita.qmd
          #   text: Trappolaggio
          - href: pages/cn/catture.qmd
            text: Catture
          - href: pages/cn/nidi.qmd
            text: Nidi
      - text: Strumenti
        menu:
          - href: pages/tools/trapSettoriTO.qmd
            text: Settori di trappolaggio
          - href: pages/tools/ricercaTrap.qmd
            text: Ricerca trappole
          - href: pages/tools/numeriLiberi.qmd
            text: ID liberi
          - href: pages/tools/attendibilita_segnalazioni.qmd
            text: Definizioni dell'attendibilità delle segnalazioni
          - href: pages/dataDictionary/index.qmd
            text: Data dictionary


      - pages/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
