project:
  type: website

website:
  title: "Vespa Velutina"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Provincia di Torino
        menu:
          - href: cartografiaTO.qmd
            text: Cartografia
          - href: trapSettoriTO.qmd
            text: Settori di trappolaggio
      # - text: Provincia di Cuneo
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

