project:
  type: website

website:
  title: "Vespa velutina"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - text: Provincia di Torino
        menu:
          - href: pages/to/attivita.qmd
            text: Attività di trappolaggio
          - href: pages/to/trapSettori.qmd
            text: Settori di trappolaggio
          - href: pages/to/cartografia.qmd
            text: Cartografia
      # - text: Provincia di Cuneo
      - pages/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

