project:
  type: website

website:
  title: "Vespa velutina"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Provincia di Torino
        menu:
          - href: pages/to/attivita.qmd
            text: Trappolaggio
          - href: pages/to/catture.qmd
            text: Catture
          - href: pages/to/trapSettori.qmd
            text: Gestione
          - href: pages/to/cartografia.qmd
            text: Cartografia
      # - text: Provincia di Cuneo
      - pages/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
