project:
  type: website

website:
  title: "vespaPiemonte"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: trapSettori.qmd
        text: Settori di trappolaggio
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

