project:
  type: website

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TWBDZMSNVY"
    anonymize-ip: true
  title: "Vespa velutina"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Provincia di Torino
        menu:
          - href: pages/to/attivita.qmd
            text: Trappolaggio
          - href: pages/to/catture.qmd
            text: Catture
          - href: pages/to/cartografia.qmd
            text: Cartografia
      # - text: Provincia di Cuneo
      - text: Strumenti
        menu:
          - href: pages/tools/trapSettoriTO.qmd
            text: Settori di trappolaggio
          - href: pages/tools/numeriLiberi.qmd
            text: Numeri liberi
          - href: pages/dataDictionary/index.qmd
            text: Data Dictionary


      - pages/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
