---
title: "Settori di trappolaggio"
description: "Informazioni per la gestione delle trappole"
lang: it-IT
format: dashboard
---

```{r setup, include=FALSE}
source("../../scripts/importGeoPackages.R")
source("../../scripts/calcoliTrappole.R")
source("../../scripts/etaBirraSettori.R")
library(ggplot2)
library(plotly)
library(pander)
```

# Settori

```{r graficoZoneBirra, echo=FALSE, warning=FALSE}
# grafico a barre orizzontali per la finestra di sostituzione della birra delle trappole
ggplot(modaEtaBirra, x = etaBirra, y = zone, fill = zone) +
 geom_linerange(aes(y=zone, xmin = minControllo, xmax = maxControllo), color = "orange",linewidth = 3*modaEtaBirra$nTrappole/max(modaEtaBirra$nTrappole)) +
 scale_y_discrete(labels= paste0(modaEtaBirra$zone, " (", modaEtaBirra$nTrappoleMin, "/", modaEtaBirra$nTrappole, ")")) +
 geom_point(aes(x = modaEtaBirra$minimControllo, y = modaEtaBirra$zone, size = 1, color = "orange")) +
  geom_vline(xintercept=Sys.Date(), linetype = "dashed", color = "red") +
  geom_text(x = Sys.Date(), y = Inf, label = "Oggi", vjust = 1, hjust = 1, color = "black") +
  {if(!is.na(data_prevista))geom_vline(xintercept=c(data_prevista), linetype = "dashed", color = c("blue"))} +
  {if(!is.na(data_prevista))geom_text(x = data_prevista, y = Inf, label = format(data_prevista, "%d/%m"), vjust = 1, hjust = 0, color = "blue")} +
#     geom_text(x = data_prevista, y = Inf, label = format(data_prevista, "%d/%m"), vjust = 1, hjust = 1, color = "blue")
# } +
 theme_minimal() +
 theme(axis.text.y = element_text(angle = 0, hjust = 1)) +
 coord_cartesian(xlim = c(min(modaEtaBirra$minControllo), Sys.Date() + 30)) +
 labs(title = "Finestra di sostituzione della birra per zona",
    x = "Tempo",
    y = "Zone",
    fill = "Zona") +
    scale_fill_brewer(palette = "Set1") +
    theme(legend.position = "none")
```
