on:
  push:
    branches: [master]
  schedule:
    - cron: '0 4 * * *'

name: backupGDrive

jobs:
  demo-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get -y install libcurl4-openssl-dev

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("devtools", "remotes", "googledrive", "purrr"))'
        
      - name: Install qfieldcloudR from GitHub
        run: Rscript -e 'devtools::install_github("livelihoods-and-landscapes/qfieldcloudR")'
        
      - name: Import data
        run: Rscript -e 'source("scripts/importFromQfieldCloud.R")'
        
      - name: Backup data
        run: Rscript -e 'source("scripts/backup.R")'
