on:
  push:
    branches: [master]
  schedule:
    - cron: '0 4 * * *'

name: backupGDrive

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      QFIELD_CLOUD_PASSWORD: ${{ secrets.QFIELD_CLOUD_PASSWORD }}
      QFIELD_CLOUD_USERNAME: ${{ secrets.QFIELD_CLOUD_USERNAME }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get -y install libcurl4-openssl-dev

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        
      - name: Import data
        run: Rscript -e 'source("scripts/importFromQfieldCloud.R")'
        
      - name: Backup data
        run: Rscript -e 'source("scripts/backup.R")'
