on:
  push:
    branches: [master]
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 19 * * *'
  release:
    types: [published]
  workflow_dispatch:

name: buildvespaPiemonte

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      QFIELD_CLOUD_PASSWORD: ${{ secrets.QFIELD_CLOUD_PASSWORD }}
      QFIELD_CLOUD_USERNAME: ${{ secrets.QFIELD_CLOUD_USERNAME }}
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    permissions:
      contents: write
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libproj-dev libgdal-dev libgeos-dev libudunits2-dev language-pack-it

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Ensure cache directory exists
        run: mkdir -p cache
        
      - name: Ensure cache directory exists
        run: mkdir -p cache/pubdata
  
      - name: Cache built data
        id: cache-data
        uses: actions/cache@v2
        with:
          path: cache
          key: build-data-${{ hashFiles('cache/**/*') }}
          restore-keys: |
            build-data-
              
  
      - name: Get remote file hash
        id: get-remote-hash
        run: |
          remote_url="https://www.datigeo-piem-download.it/direct/Geoportale/RegionePiemonte/Limiti_amministrativi/AMBITI_AMMINISTRATIVI_COMUNI1.zip"
          remote_hash=$(curl -sI "$remote_url" | grep -i 'etag' | tr -d '"' | awk '{print $2}')
          echo "remote_hash=$remote_hash" >> $GITHUB_ENV
  
      - name: Check if cache was hit
        id: check-cache
        run: |
          if [ -f "cache/pubdata/AMBITI_AMMINISTRATIVI_COMUNI1.zip" ]; then
            local_hash=$(md5sum cache/pubdata/AMBITI_AMMINISTRATIVI_COMUNI1.zip | awk '{print $1}')
            echo "local_hash=$local_hash" >> $GITHUB_ENV
            if [ "$local_hash" = "$remote_hash" ]; then
              echo "Cache hit, file is up to date"
              echo "cache_hit=true" >> $GITHUB_ENV
            else
              echo "Cache miss, file is outdated"
              echo "cache_hit=false" >> $GITHUB_ENV
            fi
          else
            echo "Cache miss, file does not exist"
            echo "cache_hit=false" >> $GITHUB_ENV
          fi
  
      - name: Download shapefile if needed
        if: env.cache_hit != 'true'
        run: |
          curl -L -o cache/pubdata/AMBITI_AMMINISTRATIVI_COMUNI1.zip "https://www.datigeo-piem-download.it/direct/Geoportale/RegionePiemonte/Limiti_amministrativi/AMBITI_AMMINISTRATIVI_COMUNI1.zip" 
  
      - name: Cache downloaded file
        uses: actions/cache@v2
        with:
          path: cache/pubdata/AMBITI_AMMINISTRATIVI_COMUNI1.zip
          key: shapefile-${{ env.remote_hash }}
          restore-keys: |
            shapefile-
    
      - name: Check if cache was hit
        run: |
          if [ -f "cache/nidi.rds" ] && [ -f "cache/trap.rds" ]; then
            echo "Cache hit, data files exist"
          else
            echo "Cache miss, data files do not exist"
          fi
  
      - name: Check and update geographical data
        run: |
          Rscript scripts/start_script_v2.R
  
      - name: Cache updated data
        uses: actions/cache@v2
        with:
          path: cache
          key: build-data-${{ hashFiles('cache/**/*') }}
        
      # - name: Other calculations
      #   run: Rscript -e 'source("scripts/complete_script_v2.R")'

      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Render and Publish"
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
