on:
  push:
    branches: [master]
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 19 * * *'
  release:
    types: [published]
  workflow_dispatch:

name: buildvespaPiemonte

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      QFIELD_CLOUD_PASSWORD: ${{ secrets.QFIELD_CLOUD_PASSWORD }}
      QFIELD_CLOUD_USERNAME: ${{ secrets.QFIELD_CLOUD_USERNAME }}
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    permissions:
      contents: write
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libproj-dev libgdal-dev libgeos-dev libudunits2-dev language-pack-it

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Ensure cache directory exists
        run: mkdir -p cache
        
      - name: Set directory permissions
        run: chmod -R 777 cache

      - name: Cache built data
        id: cache-data
        uses: actions/cache@v2
        with:
          path: |
            cache/nidi_elevation_cache.rds
            cache/trap_elevation_cache.rds
            cache/nidi_geom_checksum.txt
            cache/trap_geom_checksum.txt
          key: build-data-${{ hashFiles('cache/nidi_elevation_cache.rds', 'cache/trap_elevation_cache.rds', 'cache/nidi_geom_checksum.txt', 'cache/trap_geom_checksum.txt') }}
          restore-keys: |
            build-data-
    
      - name: Check if cache was hit
        run: |
          if [ -f "cache/nidi_elevation_cache.rds" ] && [ -f "cache/trap_elevation_cache.rds" ]; then
            echo "Cache hit, data files exist"
          else
            echo "Cache miss, data files do not exist"
          fi
  
      - name: Check and update geographical data
        run: |
          Rscript scripts/start_script_v2.R
  
      - name: Cache updated data
        uses: actions/cache@v2
        with:
          path: |
            cache/nidi_elevation_cache.rds
            cache/trap_elevation_cache.rds
            cache/nidi_geom_checksum.txt
            cache/trap_geom_checksum.txt
          key: build-data-${{ hashFiles('cache/nidi_elevation_cache.rds', 'cache/trap_elevation_cache.rds', 'cache/nidi_geom_checksum.txt', 'cache/trap_geom_checksum.txt') }}
        
      - name: Other calculations
        run: Rscript -e 'source("scripts/complete_script_v2.R")'


      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Render and Publish"
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
